name: travelapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.2.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  diacritic: ^0.1.3
  google_sign_in: ^7.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^28.1.38
  qr_flutter: ^4.1.0
  flutter_chat_bubble: ^2.0.2
  model_viewer_plus: ^1.9.3
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.3
  path_provider: ^2.1.3
  geolocator: ^10.0.0
  flutter_svg: ^2.0.7
  panorama_viewer: ^2.0.7
  flutter_osm_plugin: ^1.4.3
  audioplayers: ^6.5.1



  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/


